base_url           = "https://ccjmne.sh/blog/"
author             = "Éric NICOLAS (ccjmne)"
title              = "ccjmne's blog"
compile_sass       = true
generate_feeds     = true
build_search_index = false
default_language   = "en"
taxonomies         = [{ name = "tags" }, { name = "section" }]

[link_checker]
internal_level = "error" # "warn" is broken

[markdown]
github_alerts       = true
bottom_footnotes    = true
insert_anchor_links = "left"

[markdown.highlighting]
light_theme = "catppuccin-latte"
dark_theme  = "catppuccin-frappe"
style       = "class"

[extra.tools.dive]
name    = "dive"
repo    = "https://github.com/wagoodman/dive"
package = "extra/x86_64/dive"
manual  = "https://github.com/wagoodman/dive"

[extra.tools.docker]
name    = "docker"
repo    = "https://github.com/moby/moby"
package = "extra/x86_64/docker"
manual  = "https://docs.docker.com/"

[extra.tools.xray]
name    = "xray"
repo    = "https://github.com/h33333333/xray"
package = "aur/xray-oci-git"
manual  = "https://github.com/h33333333/xray"
