[package]
name = "compile-catppuccin-syntax"
edition = "2024"

[dependencies]
sublime-color-scheme = "0.1.4"
syntect = "5"

[[bin]]
name = "compile-catppuccin-syntax"
path = "compile-catppuccin-syntax.rs"
